// GLOBAL
export const COLLAPSE_SIDER = "COLLAPSE_SIDER";
export const DECOLLAPSE_SIDER = "DECOLLAPSE_SIDER";

// AUTH
export const AUTO_LOGIN_REQUEST = "AUTO_LOGIN_REQUEST";
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
export const AUTO_LOGIN_FAILURE = "AUTO_LOGIN_FAILURE";
export const AUTO_LOGIN_RESET = "AUTO_LOGIN_RESET";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_RESET = "LOGIN_RESET";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const SIGNUP_INSTRUCTOR_REQUEST = "SIGNUP_INSTRUCTOR_REQUEST";
export const SIGNUP_INSTRUCTOR_SUCCESS = "SIGNUP_INSTRUCTOR_SUCCESS";

// USER
export const GET_USERS = "GET_USERS";
export const SET_USERS = "SET_USERS";

export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const SET_USER_DETAIL = "SET_USER_DETAIL";

export const RESET_USER_RESET = "RESET_USER_RESET";

// INSTRUCTOR
export const CONFIRM_INSTRUCTOR = "CONFIRM_INSTRUCTOR";
export const CANCEL_INSTRUCTOR = "CANCEL_INSTRUCTOR";

// STUDENTS
export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_FINISHED = "CREATE_STUDENT_FINISHED";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_FINISHED = "UPDATE_STUDENT_FINISHED";

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_FINISHED = "DELETE_STUDENT_FINISHED";

export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const ADD_STUDENT_FINISHED = "ADD_STUDENT_FINISHED";

export const GET_INSTRUCTORS_OF_STUDENT_REQUEST =
  "GET_INSTRUCTORS_OF_STUDENT_REQUEST";
export const GET_INSTRUCTORS_OF_STUDENT_FINISHED =
  "GET_INSTRUCTORS_OF_STUDENT_FINISHED";

export const ADD_STUDENT_TO_INSTRUCTORS_REQUEST =
  "ADD_STUDENT_TO_INSTRUCTORS_REQUEST";
export const ADD_STUDENT_TO_INSTRUCTORS_FINISHED =
  "ADD_STUDENT_TO_INSTRUCTORS_FINISHED";

export const GET_STUDENTS_OF_INSTRUCTOR_REQUEST =
  "GET_STUDENTS_OF_INSTRUCTOR_REQUEST";
export const GET_STUDENTS_OF_INSTRUCTOR_FINISHED =
  "GET_STUDENTS_OF_INSTRUCTOR_FINISHED";

export const ADD_STUDENTS_TO_INSTRUCTOR_REQUEST =
  "ADD_STUDENTS_TO_INSTRUCTOR_REQUEST";
export const ADD_STUDENTS_TO_INSTRUCTOR_FINISHED =
  "ADD_STUDENTS_TO_INSTRUCTOR_FINISHED";

// SHAPE
export const GET_SHAPES = "GET_SHAPES";
export const SET_SHAPES = "SET_SHAPES";
export const ADD_SHAPES = "ADD_SHAPES";

export const GET_MORE_SHAPES = "GET_MORE_SHAPES";
export const SET_MORE_SHAPES = "SET_MORE_SHAPES";

export const GET_SHAPE_DETAIL_REQUEST = "GET_SHAPE_DETAIL_REQUEST";
export const GET_SHAPE_DETAIL_FINISHED = "GET_SHAPE_DETAIL_FINISHED";

export const CREATE_SHAPE_REQUEST = "CREATE_SHAPE_REQUEST";
export const CREATE_SHAPE_FINISHED = "CREATE_SHAPE_FINISHED";

export const UPDATE_SHAPE_REQUEST = "UPDATE_SHAPE_REQUEST";
export const UPDATE_SHAPE_FINISHED = "UPDATE_SHAPE_FINISHED";

export const SET_DRAG_ITEM = "SET_DRAG_ITEM";

// QUESTION
export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST";
export const CREATE_QUESTION_FINISHED = "CREATE_QUESTION_FINISHED";
export const QUESTION_FORM_RESET = "QUESTION_FORM_RESET";

export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_FINISHED = "UPDATE_QUESTION_FINISHED";

export const ADD_SHAPE_TO_QUESTION = "ADD_SHAPE_TO_QUESTION";
export const REMOVE_SHAPE_FROM_QUESTION = "REMOVE_SHAPE_FROM_QUESTION";

export const ADD_SHAPE_TO_CHOICES = "ADD_SHAPE_TO_CHOICES";
export const REMOVE_SHAPE_TO_CHOICES = "REMOVE_SHAPE_TO_CHOICES";

export const RESET_ACTIVE_QUESTION = "RESET_ACTIVE_QUESTION";

export const GET_QUESTION_LIST_REQUEST = "GET_QUESTION_LIST_REQUEST";
export const GET_QUESTION_LIST_FINISHED = "GET_QUESTION_LIST_FINISHED";

export const GET_QUESTION_CONFIGS_REQUEST = "GET_QUESTION_CONFIGS_REQUEST";
export const GET_QUESTION_CONFIGS_FINISHED = "GET_QUESTION_CONFIGS_FINISHED";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_FINISHED = "DELETE_QUESTION_FINISHED";

export const GET_QUESTION_DETAIL_REQUEST = "GET_QUESTION_DETAIL_REQUEST";
export const GET_QUESTION_DETAIL_FINISHED = "GET_QUESTION_DETAIL_FINISHED";

export const SET_CORRECT_ANSWER = "SET_CORRECT_ANSWER";

export const ASSIGN_QUESTION_ID = "ASSIGN_QUESTION_ID";
export const SIGN_QUESTION = "SIGN_QUESTION";

// QUIZ
export const ADD_QUESTION_TO_QUIZ = "ADD_QUESTION_TO_QUIZ";
export const REMOVE_QUESTION_FROM_QUIZ = "REMOVE_QUESTION_FROM_QUIZ";

export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_FINISHED = "CREATE_QUIZ_FINISHED";

export const UPDATE_QUIZ_REQUEST = "UPDATE_QUIZ_REQUEST";
export const UPDATE_QUIZ_FINISHED = "UPDATE_QUIZ_FINISHED";

export const ASSIGN_QUIZ_TO_STUDENT_REQUEST = "ASSIGN_QUIZ_TO_STUDENT_REQUEST";
export const ASSIGN_QUIZ_TO_STUDENT_FINISHED =
  "ASSIGN_QUIZ_TO_STUDENT_FINISHED";

export const GET_STUDENTS_OF_QUIZ_BY_INSTRUCTOR_REQUEST =
  "GET_STUDENTS_OF_QUIZ_BY_INSTRUCTOR_REQUEST";
export const GET_STUDENTS_OF_QUIZ_BY_INSTRUCTOR_FINISHED =
  "GET_STUDENTS_OF_QUIZ_BY_INSTRUCTOR_FINISHED";

export const DELETE_QUIZ_REQUEST = "DELETE_QUIZ_REQUEST";
export const DELETE_QUIZ_FINISHED = "DELETE_QUIZ_FINISHED";

export const GET_QUIZ_LIST_REQUEST = "GET_QUIZ_LIST_REQUEST";
export const GET_QUIZ_LIST_FINISHED = "GET_QUIZ_LIST_FINISHED";

export const GET_QUIZ_DETAIL_REQUEST = "GET_QUIZ_DETAIL_REQUEST";
export const GET_QUIZ_DETAIL_FINISHED = "GET_QUIZ_DETAIL_FINISHED";

export const RESET_ACTIVE_QUIZ = "RESET_ACTIVE_QUIZ";
export const QUIZ_FORM_RESET = "QUIZ_FORM_RESET";

export const FINISH_QUIZ_REQUEST = "FINISH_QUIZ_REQUEST";
export const FINISH_QUIZ_FINISHED = "FINISH_QUIZ_FINISHED";

// SCORE
export const GET_SCORE_LIST_REQUEST = "GET_SCORE_LIST_REQUEST";
export const GET_SCORE_LIST_FINISHED = "GET_SCORE_LIST_FINISHED";

export const GET_SCORE_DETAIL_REQUEST = "GET_SCORE_DETAIL_REQUEST";
export const GET_SCORE_DETAIL_FINISHED = "GET_SCORE_DETAIL_FINISHED";

// CONFIG
export const GET_FIREBASE_CONFIG_REQUEST = "GET_FIREBASE_CONFIG_REQUEST";
export const GET_FIREBASE_CONFIG_FINISHED = "GET_FIREBASE_CONFIG_FINISHED";
