// AUTH
export const AUTO_LOGIN_REQUEST = "AUTO_LOGIN_REQUEST";
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
export const AUTO_LOGIN_FAILURE = "AUTO_LOGIN_FAILURE";
export const AUTO_LOGIN_RESET = "AUTO_LOGIN_RESET";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const INSTRUCTOR_LOGIN_SUCCESS = "INSTRUCTOR_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_RESET = "LOGIN_RESET";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const TOGGLE_USER_INFO = "TOGGLE_USER_INFO";

export const SIGNUP_INSTRUCTOR_REQUEST = "SIGNUP_INSTRUCTOR_REQUEST";
export const SIGNUP_INSTRUCTOR_SUCCESS = "SIGNUP_INSTRUCTOR_SUCCESS";

// STUDENTS
export const GET_STUDENTS = "GET_STUDENTS";
export const SET_STUDENTS = "SET_STUDENTS";

export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_FINISHED = "CREATE_STUDENT_FINISHED";

// SHAPE
export const GET_SHAPES = "GET_SHAPES";
export const SET_SHAPES = "SET_SHAPES";

export const GET_MORE_SHAPES = "GET_MORE_SHAPES";
export const SET_MORE_SHAPES = "SET_MORE_SHAPES";

export const GET_SHAPE_DETAIL_REQUEST = "GET_SHAPE_DETAIL_REQUEST";
export const GET_SHAPE_DETAIL_FINISHED = "GET_SHAPE_DETAIL_FINISHED";

// QUESTION
export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST";
export const CREATE_QUESTION_FINISHED = "CREATE_QUESTION_FINISHED";
export const QUESTION_FORM_RESET = "QUESTION_FORM_RESET";

export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_FINISHED = "UPDATE_QUESTION_FINISHED";

export const ADD_SHAPE_TO_QUESTION = "ADD_SHAPE_TO_QUESTION";
export const REMOVE_SHAPE_TO_QUESTION = "REMOVE_SHAPE_TO_QUESTION";

export const ADD_SHAPE_TO_CHOICES = "ADD_SHAPE_TO_CHOICES";
export const REMOVE_SHAPE_TO_CHOICES = "REMOVE_SHAPE_TO_CHOICES";

export const RESET_ACTIVE_QUESTION = "RESET_ACTIVE_QUESTION";

export const GET_QUESTION_LIST_REQUEST = "GET_QUESTION_LIST_REQUEST";
export const GET_QUESTION_LIST_FINISHED = "GET_QUESTION_LIST_FINISHED";

export const GET_QUESTION_CONFIGS_REQUEST = "GET_QUESTION_CONFIGS_REQUEST";
export const GET_QUESTION_CONFIGS_FINISHED = "GET_QUESTION_CONFIGS_FINISHED";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_FINISHED = "DELETE_QUESTION_FINISHED";

export const GET_QUESTION_DETAIL_REQUEST = "GET_QUESTION_DETAIL_REQUEST";
export const GET_QUESTION_DETAIL_FINISHED = "GET_QUESTION_DETAIL_FINISHED";

export const SET_CORRECT_ANSWER = "SET_CORRECT_ANSWER";
