// AUTH
export const AUTO_LOGIN_REQUEST = "AUTO_LOGIN_REQUEST";
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
export const AUTO_LOGIN_FAILURE = "AUTO_LOGIN_FAILURE";
export const AUTO_LOGIN_RESET = "AUTO_LOGIN_RESET";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const INSTRUCTOR_LOGIN_SUCCESS = "INSTRUCTOR_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_RESET = "LOGIN_RESET";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const TOGGLE_USER_INFO = "TOGGLE_USER_INFO";

export const SIGNUP_INSTRUCTOR_REQUEST = "SIGNUP_INSTRUCTOR_REQUEST";
export const SIGNUP_INSTRUCTOR_SUCCESS = "SIGNUP_INSTRUCTOR_SUCCESS";

// STUDENTS
export const GET_STUDENTS = "GET_STUDENTS";
export const SET_STUDENTS = "SET_STUDENTS";

export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_FINISHED = "CREATE_STUDENT_FINISHED";

// SHAPE
export const GET_SHAPES = "GET_SHAPES";
export const SET_SHAPES = "SET_SHAPES";

export const GET_SHAPE_DETAIL_REQUEST = "GET_SHAPE_DETAIL_REQUEST";
export const GET_SHAPE_DETAIL_FINISHED = "GET_SHAPE_DETAIL_FINISHED";
